# Education Control System - Spring Boot Configuration

spring:
  # Application Info
  application:
    name: ecs-web
  
  # Web Configuration
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  
  # Thymeleaf Configuration
  thymeleaf:
    cache: false # For development
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  
  # Database Configuration - H2 for Development
  datasource:
    url: jdbc:h2:mem:ecsdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop # For development, use 'validate' for production
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true # For development
    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': true
        jdbc:
          '[batch_size]': 20
        '[order_inserts]': true
        '[order_updates]': true
  
  # H2 Console (for development only)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  
  # Security Configuration
  security:
    user:
      name: admin
      password: ***REMOVED***
      roles: ADMIN
  
  # Jackson JSON Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Europe/Kiev
    date-format: "dd.MM.yyyy"
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true
  error:
    include-message: always
    include-binding-errors: always

# Logging Configuration
logging:
  config: classpath:logback-spring.xml
  level:
    '[com.brainacad.ecs]': INFO
    '[org.springframework]': WARN
    '[org.hibernate]': WARN
    '[org.hibernate.SQL]': DEBUG
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ecs-web.log
    max-size: 10MB
    max-history: 30

# Management & Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# Application Custom Properties
ecs:
  # Business Logic Configuration
  course:
    max-students: 30
    min-duration-days: 1
    max-duration-days: 365
  
  # File Storage Configuration
  file:
    upload-dir: uploads/
    max-size: 10MB
  
  # API Configuration
  api:
    version: v1
    base-path: /api/v1
    
# Development Profile Settings
---
spring:
  config:
    activate:
      on-profile: dev
  
  # Development Database
  datasource:
    url: jdbc:h2:file:./data/ecsdb
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    '[com.brainacad.ecs]': DEBUG
    '[org.springframework.security]': DEBUG

---
# Production Profile Settings  
spring:
  config:
    activate:
      on-profile: prod
      
  # Production Database - PostgreSQL
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ecsdb}
    username: ${DATABASE_USERNAME:ecs_user}
    password: ${DATABASE_PASSWORD:ecs_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 10
  
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    '[com.brainacad.ecs]': WARN
    '[org.springframework]': WARN
    root: WARN
  
  # H2 Console disabled in production
  h2:
    console:
      enabled: false
      
# Logging for production
logging:
  level:
    com.brainacad.ecs: INFO
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
