# Education Management System - Spring Boot Configuration - Default
spring:
  profiles:
    active: dev
  # Application Info  
  application:
    name: "@project.name@"
    version: "@project.version@"
    description: "@project.description@"

  # Database Configuration - PostgreSQL
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/ecs}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 20
      minimum-idle: 10
      leak-detection-threshold: 60000

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # Use 'update' for development, 'validate' for production
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true # For development
    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': true
        '[generate_statistics]': true
        jdbc:
          '[batch_size]': 20
        '[order_inserts]': true
        '[order_updates]': true
  
  # Thymeleaf Configuration
  thymeleaf:
    cache: false # For development
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  
  # Jackson JSON Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Europe/Kiev
    date-format: "dd.MM.yyyy"
  
  # File Upload Configuration
  servlet:
    multipart:
      max-file-size: ${UPLOAD_MAX_SIZE:10MB}
      max-request-size: ${UPLOAD_MAX_SIZE:10MB}
  
  # Email SMTP Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Server Configuration
server:
  port: ${SERVER_PORT:8080}
  servlet:
    session:
      timeout: ${ECS_SESSION_TIMEOUT:30m}
      cookie:
        name: ${ECS_SESSION_COOKIE_NAME:JSESSIONID}
        secure: ${ECS_SESSION_COOKIE_SECURE:false}
        http-only: ${ECS_SESSION_COOKIE_HTTP_ONLY:true}
        same-site: ${ECS_SESSION_COOKIE_SAME_SITE:lax}
    context-path: /
    encoding:
      charset: UTF-8
      force: true
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

# Logging Configuration
logging:
  config: classpath:logback-spring.xml
  level:
    '[io.github.vibondarenko.clavionx]': ${LOG_LEVEL_APP:WARN}
    '[org.springframework]': WARN
    '[org.springframework.security]': WARN
    '[org.springframework.security.web.authentication]': ERROR
    '[org.hibernate]': WARN
    '[org.hibernate.SQL]': WARN
    root: ${LOG_LEVEL_ROOT:WARN}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ecs-web.log
    max-size: 10MB
    max-history: 30

# Management & Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: when-authorized
  info:
    env:
      enabled: true

# Application Custom Properties
ecs:
  # Business Logic Configuration
  course:
    max-students: 30
    min-duration-days: 1
    max-duration-days: 365

  # File Storage Configuration
  file:
    upload-dir: uploads/
    max-size: 10MB
  
  # API Configuration
  api:
    version: v1
    base-path: /api/v1

  # Session Management Configuration
  session:
    max-sessions-per-user: ${ECS_MAX_SESSIONS_PER_USER:5}
    inactive-timeout-hours: ${ECS_INACTIVE_TIMEOUT_HOURS:24}
    cleanup-old-sessions-days: ${ECS_CLEANUP_OLD_SESSIONS_DAYS:30}
    timeout-minutes: ${ECS_SESSION_TIMEOUT_MINUTES:30}
    cookie-name: ${ECS_SESSION_COOKIE_NAME:JSESSIONID}
    cookie-max-age-seconds: ${ECS_SESSION_COOKIE_MAX_AGE:1800}
    cookie-secure: ${ECS_SESSION_COOKIE_SECURE:false}
    cookie-http-only: ${ECS_SESSION_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${ECS_SESSION_COOKIE_SAME_SITE:Lax}

# Security custom properties
security:
  remember-me:
    validity-seconds: 86400
