-- Migration script for Two-Factor Authentication support
-- Add 2FA fields to users table and create two_factor_tokens table

-- Add Two-Factor Authentication columns to users table
ALTER TABLE users 
ADD COLUMN two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN preferred_two_factor_method VARCHAR(20) NULL;

-- Create two_factor_tokens table
CREATE TABLE IF NOT EXISTS two_factor_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    verification_code VARCHAR(6) NOT NULL,
    method VARCHAR(20) NOT NULL CHECK (method IN ('EMAIL','PHONE','BOTH')),
    user_id BIGINT NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    used BOOLEAN NOT NULL DEFAULT FALSE,
    attempts INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 3,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    used_at TIMESTAMP NULL,
    
    -- Foreign key constraint
    CONSTRAINT fk_two_factor_tokens_user 
        FOREIGN KEY (user_id) REFERENCES users(id) 
        ON DELETE CASCADE
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_two_factor_tokens_user_id ON two_factor_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_two_factor_tokens_expires_at ON two_factor_tokens(expires_at);
CREATE INDEX IF NOT EXISTS idx_two_factor_tokens_used ON two_factor_tokens(used);
CREATE INDEX IF NOT EXISTS idx_two_factor_tokens_user_code ON two_factor_tokens(user_id, verification_code);

-- Add comments for documentation
ALTER TABLE users 
COMMENT = 'User accounts with authentication and two-factor support';

ALTER TABLE two_factor_tokens 
COMMENT = 'Two-factor authentication verification tokens';

-- Add column comments
ALTER TABLE users 
MODIFY COLUMN two_factor_enabled BOOLEAN NOT NULL DEFAULT FALSE 
COMMENT 'Whether 2FA is enabled for this user',
MODIFY COLUMN preferred_two_factor_method VARCHAR(20) NULL 
COMMENT 'Preferred 2FA method: EMAIL, PHONE, or BOTH';

-- Update activity types for 2FA tracking (if using enum, this might need adjustment)
-- This is informational - actual activity types are handled in the application
/* 
New activity types added:
- TWO_FACTOR_CODE_SENT
- TWO_FACTOR_VERIFIED  
- TWO_FACTOR_ENABLED
- TWO_FACTOR_DISABLED
*/
